boostcampwm-2024/web05-Denamu

.gitignore
.vscode/settings.json
client/.gitignore
client/.prettierrc
client/README.md
client/eslint.config.js
client/index.html
client/package-lock.json
client/package.json
client/postcss.config.js
client/src/App.tsx
client/src/index.css
client/src/main.tsx
client/src/pages/Home.tsx
client/src/vite-env.d.ts
client/tailwind.config.js
client/tsconfig.app.json
client/tsconfig.json
client/tsconfig.node.json
client/vite.config.ts

```
commit 메세지가 적절한지 확인하기
적절한 브랜치로 요청했는지 확인하기
PR이 승인되면 해당 브랜치 삭제하기
```
---
- close #2 
---
- 필요한 라이브러리 설치
- 개발 환경 세팅 (eslint + prettier)

📦 chore: 프론트엔드 개발 환경 세팅

---

server/.eslintrc.js
server/.gitignore
server/.prettierrc
server/README.md
server/nest-cli.json
server/package-lock.json
server/package.json
server/src/app.module.ts
server/src/main.ts
server/test/app.e2e-spec.ts
server/test/jest-e2e.json
server/tsconfig.build.json
server/tsconfig.json

📦 chore: 초기 의존성 설치

---

commitlint.config.js
lefthook.yml
package-lock.json
package.json

-   close #35
- 커밋 린트 설정
- 커밋 컨벤션에 맞지않는 커밋 메시지를 작성 시 커밋이 reject 됩니다.

📦 chore: 커밋린트 설정

---

commitlint.config.js
lefthook.yml

-   close #35
-   lefthook 오타 발견 commit_msg -> commit-msg
-   commit convention 대괄호(`[]`) 제거

📦 chore: 커밋린트 수정

---

.github/workflows/deploy.yml
server/ecosystem.config.js
server/src/app.module.ts

📦 chore: CD 파이프라인 작성

---

server/logger.config.ts
server/package-lock.json
server/package.json
server/src/app.module.ts
server/src/common/logger/logger.config.ts
server/src/common/logger/logger.module.ts

- Close #31
- winston을 활용해서 로거를 등록했습니다. script는 아래와 같이 작성했습니다.
- 로깅 파일 쓰기 확인
- 로깅 콘솔 출력 확인
- 사용 방법

📦 chore: Nest 환경 로거 등록

---

.github/workflows/deploy.yml
server/.gitignore
server/src/configs/.env.db.test

-   close #27
- `.env.db.test` 정적 데이터로 커밋
- github Action 정적 데이터 제거
- github Action에서 수행할 디렉토리 생성 위치 수정 `server/src/configs` -> `src/configs`

🐛 fix: CI/CD configs 디렉토리 경로 수정, 피드백 반영

---

.github/workflows/deploy.yml

- `deploy.yml` 스크립트에 존재하던 오탈자 수정

🐛 fix: CD 스크립트 오탈자 수정

---

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/api/mockApi.ts
client/src/components/common/Card/PostCard.tsx
client/src/components/common/LazyImage.tsx
client/src/components/common/LoadingIndicator.tsx
client/src/components/sections/LatestSection.tsx
client/src/constants/dummyData.ts
client/src/hooks/useInfiniteScrollQuery.ts
client/src/lib/utils.ts
client/src/types/post.ts
package-lock.json
package.json
rss-notifier/.gitignore
rss-notifier/package-lock.json
rss-notifier/package.json
rss-notifier/src/db-access.ts
rss-notifier/src/logger.ts
rss-notifier/src/main.ts
rss-notifier/src/rss-notifier.ts
rss-notifier/src/types.ts
rss-notifier/tsconfig.json

- #23 
rss polling 동작을 수행하는 `rss-notifier` 모듈을 작성하였습니다.
- **`db-access.ts`** : db와 액세스 하는 두가지 동작 **(`blogs` 테이블로 부터 rss들을 조회)** 을 담당하는 모듈입니다.
- **`rss-notifier,ts`** : 실행 시간으로부터 1시간 이내에 작성된 피드를 발견하면, 해당 피드들의 `blog_id, pub_date, title, link, imageUrl` 데이터들을 파싱해 반환하는 모듈입니다.
- **`logger.js`** : 로깅에 필요한 설정들을 선언하는 모듈입니다.
`rss-notifier`의 확장성, 서버 안정화를 위한 유연한 로드밸런싱 등을 목적으로 `Nest.js` 프로젝트에 해당 로직을 포함시키지 않고, 독립적인 모듈로 분리하였습니다.
> [!IMPORTANT]
> **아직 `rss-notifier` 모듈은 pm2 실행 범위에 포함되어있지 않습니다.** 
> 해당 부분은 PR을 별도로 분리하여 이어 작업할 예정 입니다. `Nest.js` 애플리케이션과 `rss-notifier`를 같이 실행시키기 위해서는 기존의 실행 프로세스를 조금 변경해야 하는 것을 인지하여 현재 작업 중에 있습니다.
> 해당 작업 내용은 pm2의 cron을 사용한 정기 실행 로직 작성입니다.
- **`blog` 테이블**
시험삼아 제 블로그와 향로님의 블로그 rss를 등록해 두었습니다.
- **`rss-notifier` 모듈 실행**
검색 시간을 1시간으로 설정 시 최근 작성한 게시글이 없어 조회가 불가능하여 임시적으로 조회 기간을 …

✨ feat: rss-notifier 모듈 구현

---

server/src/common/swagger/swagger.ts
server/src/main.ts

-   close #63
-   처음에는 `/api`로 하려고 했는데, 이럴 경우 api 동작과 겹쳐 혼란이 있을 것 같아 `/api-docs` 로 경로를 변경하였습니다.
1. Swagger 환경 설정
2. Swagger 웹 정보 입력

📦 chore: swagger 환경 구축

---

client/src/components/layout/Header.tsx

중복된 import 해결
머지할때 확인안하고 했다가 sidebar 중복 import가 생겨서 해결하고 다시 pr 날립니다.

🐛 fix: Header컴포넌트 중복 import 제거

---

.cz-config.js
commitlint.config.js

-   close #35
-   정말 사소한 작업들 ex) 글 변경, 코드 정리, 사용하지 않는 import 문 제거, prettier 적용 등을 위한 타입이 없었다.
-   🧼 clean 태그 추가

📦 chore: commitizen clean 태그 추가

---

server/package.json
server/src/main.ts

-   close #88 
- FE 개발 오리진, `netlify` 정적 배포 오리진 CORS 허용
개발 및 배포간 CORS 정책을 허용해주기 위해 설정을 추가하였습니다.

✨ feat: CORS 허용 설정

---

.github/workflows/deploy.yml

- deploy 스크립트에 production Port 설정 환경변수 추가

🐛 fix: production-port 변경

---

server/test/rss/rss.e2e-spec.ts

-   close #10
-   테스트 코드 rssURL -> rssUrl 변경

✅ test:  RSS 신청 테스트 코드 rssURL -> rssUrl 변경

---

client/src/api/instance.ts
client/src/components/RssRegistration/RssRegistrationModal.tsx
client/src/types/rss.ts

- close #107
- rss등록시 타입 소문자로 변경
rssURL -> rssUrl로 변경

🐛 fix: rss등록시 타입 소문자로 변경

---

server/src/feed/feed.controller.ts

-   close #19
-   API 명세에 맞춰서 trendData -> data 수정

🧼 clean: trendData -\> data API 명세에 맞춰서 작성

---

ecosystem.config.js
server/src/chat/chat.gateway.ts

- PM2 프로세스 수 1으로 조정
- chat History 레디스에서 조회 후 역순정렬 처리
핫픽스 피드백 반영 PR 입니다.

🐛 fix: PM2 프로세스 수 조정, chat history 역순

---

server/src/feed/feed.service.ts

- 검색 결과 가중치를 사용해 상위 순으로 정렬
ngram 파싱의 문제점으로, 기존 방식은 검색 가중치와 관계없이 생성일자를 기준으로 검색후 반환 했습니다.
허나, 이렇게되면
"부스트" 라는 단어를 검색하면 다음과 같은 순으로 결과가 반환되었습니다.
> title: 러스트, createdAt: 2024-11-21
title: 부스트, createdAt: 2024-11-20
이러한 문제를 개선하기 위하여 `MATCH` 쿼리의 결과값(유사도 [상대값])을 함께 select하여 이 유사도를 사용해 우선적으로 정렬한 결과를 반환토록 하였습니다.
- `부스트`를 기준으로 검색 시 조금더 연관도가 높은 "부스트캠프 멤버십"이 가장 상단에 노출됨.

✨ feat: 검색 결과 relevance 기반 정렬 구현

---

server/src/admin/admin.api-docs.ts
server/src/feed/feed.api-docs.ts
server/src/rss/rss.api-docs.ts

-   close #189 
**Swagger 작성 방법이 팀원마다 달라 일관성을 해쳐 코드 일관성 점검의 필요성 대두**
- **`properties` 기재법**
성공 응답 예제에만 기재합니다.
성공 응답을 제외한 응답에는 `message` 데이터만 전달되기에, 불필요하게 `properties`를 반복할 필요가 없습니다.
- **배열 형태의 데이터 응답시**
```typescript
properties: {
data: {
type: 'array',
items: {
type: 'object',
properties: {
...
}
```
과 같은 형태로 기재해 주시면 됩니다.

📝 docs: swagger 데코레이터 코드 일관성 개선

---

client/src/components/chat/Chat.tsx
client/src/components/layout/Header.tsx
client/src/components/search/SearchButton.tsx
client/src/components/search/SearchResults/SearchResultList.tsx
client/src/components/ui/sidebar.tsx

-   close #217 
- 헤더의 검색 버튼 스타일 수정

♻️ refactor: 헤더 검색 버튼 스타일 수정, 채팅 버튼 스타일 수정

---

client/package-lock.json

🐛 fix: 의존성 핫픽스

---

client/src/components/RssRegistration/RssRegistrationModal.tsx
client/src/components/chat/Chat.tsx
client/src/components/chat/ChatButton.tsx
client/src/components/chat/layout/ChatHeader.tsx
client/src/components/chat/layout/ChatSection.tsx
client/src/components/search/SearchButton.tsx

-   채팅창 최대 인원 제한
-   채팅 버튼 스타일 수정

♻️ refactor: 채팅창 500명 제한

---

client/src/components/layout/Header.tsx

🐛 fix: 헤더 버튼 zindex 수정

---

client/src/components/chat/layout/ChatFooter.tsx
client/src/components/layout/Header.tsx

-  ChatFooter.tsx
```
<SheetFooter className="flex items-center p-2">
<Input
placeholder="메시지를 입력하세요"
value={message}
onChange={(e) => setMessage(e.target.value)}
className="rounded-r-none"
/>
<Button className="bg-primary hover:bg-[#2ECC71] text-white !ml-0 rounded-l-none" onClick={handleSendMessage}>
<Send />
</Button>
</SheetFooter>
```
- 전
- 후

💄 style: 채팅 footer 스타일 수정

---

README.md

-   close #248
- 로고 최신 버전으로 변경
- 기술 스택 이미지 추가
- 서비스 가는 버튼 구현
- 위키 페이지 이동 링크 추가

📝 docs: readme 내용 보완

---

server/test/statistic/platform.e2e-spec.ts

-   close #205
-   블로그 플랫폼별 통계 API 테스트 코드 팀 내 테스트 컨벤션에 맞춰 작성

✅ test: 블로그 플랫폼별 통계 API 테스트 코드 작성

---

server/test/rss/dto/rss-register.dto.spec.ts
server/test/rss/rss.e2e-spec.ts

-   close #10
-   POST /api/rss API 테스트 코드 작성
- RssRegisterDto 테스트 코드 분리
- RssReigsterDto 테스트 코드 작성

✅ test: post rss API 테스트 코드 작성

---

server/src/admin/admin.controller.ts
server/test/admin/logout.e2e-spec.ts

-   close #222
-   logout 응답 코드 200 -> 201 변경
- logout API 테스트 코드 작성

✅ test: 로그아웃 API 테스트 코드 작성

---

server/package-lock.json
server/package.json
server/src/chat/chat.gateway.ts

-   close #271 
- 채팅 서버 자정 알림 이벤트 작성
`node-cron` 모듈을 활용해 서버 OS 시간 기준 자정이 되면 `message` 이벤트가 발행됩니다.
해당 이벤트의 payload의 `username` 은 말씀주신대로 `system` 입니다.
클라이언트 측에서는 이전에 이야기 나누었던 대로 처리 해주시면 됩니다 😄

✨ feat: 채팅 자정 알림 구현

---

server/src/chat/chat.gateway.ts

자정을 알려주는 메시지가 레디스에 저장되지 않아, 정상적으로 확인할 수 없는 문제가 있었습니다.
그리하여 레디스에 저장하는 부분을 함수로 분리하고, 활용할 수 있도록 처리하였습니다.

🐛 fix: 레디스 저장로직 자정 알림 이벤트에도 추가

---

client/package-lock.json
client/src/components/common/Card/PostCardContent.tsx

-   close #296 
```
const [isValidImage, setIsValidImage] = useState<boolean>(true);
const authorInitial = post.author?.charAt(0)?.toUpperCase() || "?";
const data = `https://api.denamu.site/files/${post.blogPlatform}-icon.svg`;
return (
<CardContent className="p-0">
<div className="relative -mt-6 ml-4 mb-3">
<Avatar className="h-8 w-8 ring-2 ring-background cursor-pointer">
{isValidImage ? (
<img
src={data}
alt={post.author}
className="w-full h-full"
onError={() => {
setIsValidImage(false);
}}
/>
) : (
<AvatarFallback className="text-xs bg-slate-200">{authorInitial}</AvatarFallback>
)}
</Avatar>
</div>
```
- 이미지가 유효한지 상태를 통해 체크
- 유효하지 않은 이미지라면 onError함수를 통해 앞 한글자를 출력하도록 수정

🐛 fix:블로그 이미지가 없을때 블로그명 이 나오도록 수정

---

feed-crawler/src/main.ts
feed-crawler/src/repository/feed.repository.ts
feed-crawler/src/repository/rss.repository.ts

현재 #314 PR 이후로 `feed-crawler`에 오탈자가 있어 실행되지 않고 있어 처리 완료하였습니다.

🐛 fix: import 및 경로 오탈자 수정

---

server/src/activity/entity/activity.entity.ts
server/src/activity/module/activity.module.ts
server/src/activity/repository/activity.repository.ts
server/src/app.module.ts
server/src/user/entity/user.entity.ts
server/src/user/module/user.module.ts
server/src/user/repository/user.repository.ts

태스크 작성 후 첨부하겠습니다.
지난 회의때 나왔던 요구사항 설계서를 기반으로, 사용자 및 사용자 활동 테이블을 작성하였습니다.
ERD의 요구사항대로 TypeORM Entity 및 커스텀 Repository 를 작성하였습니다.

✨ feat: User, Activity 엔티티 및 기본 레포지토리 작성

---

.github/workflows/deploy_server.yml
docker-compose/docker-compose.prod.yml
feed-crawler/docker/Dockerfile.dev
feed-crawler/docker/Dockerfile.local

-   close #327
-   Docker Compose 파일에서 infra 부분이 include 잘 못 되어 있었음
- Server CI/CD시 AI_API는 필요없으니 제거

🐛 fix: docker compose 운영 인프라 include 오류

---

package.json

-   close #327
-  close #326
-   매번 긴 명령어 치기 힘들어서 추상화를 위해 package.json에 작성
- 프로젝트 메인 디렉토리에서
```shell
npm run start:dev
npm run start:local
```
을 수행할 경우 동작합니다.

📦 chore: 간편하게 Docker-Compose 실행하기

---

.github/workflows/deploy_feed-crawler.yml
.github/workflows/deploy_server.yml

-   close #328
-   feed Crawler와 app이 mysql과 Redis와 의존적이다 보니, MySQL과 Redis 서비스가 재시작되는 문제가 있었다.
-   CI/CD에서 의존성 제거하기

📦 chore: cI/CD Ubuntu 환경변수 추가

---

server/src/user/service/user.service.ts

기존에 레디스 인증 완료 후 기존 키 삭제 처리가 포함되지 않은 부분을 처리 하였습니다.

🐛 fix: 유저 인증 로직에 레디스 키 삭제 구문 추가

---

client/src/components/chart/BarChartItem.tsx

-   close #362 
-   viewCount에서 조회수로 수정
-   기존 디자인 그대로 구현

🐛 fix: 바 차트 툴팁 조회수, 색상 박스 변경

---

package.json

-   close #326
-   npm run start:dev 명령어 수정

🐛 fix: 도커 실행 명령 수정

---

docker-compose/init.sql

-   close #326
-   ID: test@test.com
- PASSWORD: test1234!
- ID: test1234
- PASSWORD: test1234!
-   태그 데이터 삽입
- 요약 데이터 삽입
- 사용자 테스트 계정 삽입
- 운영자 테스트 계정 삽입
- 댓글 데이터 삽입

📦 chore: 태그 및 요약 내용, 개발용 사용자 계정 추가

---

server/src/migration/1747678294586-CreateProvider.ts

OAuth Provider 엔티티에 대한 마이그레이션 파일을 작성하였습니다.

✨ feat: oauth provider 마이그레이션 파일 작성

---

client/src/components/search/SearchResults/SearchResultItem.tsx
client/src/hooks/common/usePostCardActions.ts
client/src/pages/PostDetailPage.tsx

🐛 fix: 검색시 디테일 페이지로 이동

---

server/src/user/api-docs/updateUser.api-docs.ts
server/src/user/controller/user.controller.ts
server/src/user/dto/request/update-user.dto.ts
server/src/user/service/user.service.ts
server/test/user/dto/update-user.dto.spec.ts
server/test/user/e2e/update-profile.e2e-spec.ts

-   close #421
사용자 정보의 일부를 수정할 수 있는 API를 구현하였습니다.
프로필 이미지와 같은 경우는 파일 업로드 파이프라인 설계가 끝나면 일부 변경 될 예정입니다. 이 부분 참고하주시면 감사하겠습니다 :)

✨ feat: 유저 정보 수정 API 구현

---

.github/workflows/deploy_server.yml

레포지토리 시크릿과 배포 스크립트 내 누락된 깃헙 클라이언트 환경변수를 추가하였습니다.
깃헙 레포지토리 시크릿에 해당하는 환경변수명은 `GITHUB~` 로 시작할 수 없는 규칙이 존재해 시크릿 변수명만 `GIT~` 으로 설정해두었습니다.

✨ feat: 깃헙 oauth 클라이언트 환경변수 추가

---

.github/workflows/deploy_feed-crawler.yml
.github/workflows/deploy_server.yml

> **우측** : 약 2달전 deploy Actions 로그
> **좌측** : 현재 deploy Actions 로그
`--force-recreate` 옵션을 CI/CD 스크립트에 추가해 위와 같이 컨테이너 재생성에 실패하는 경우를 방지하였습니다.

🐛 fix: 컨테이너 재생성 실패문제 해결

---

client/docker/Dockerfile.local
client/vite.config.ts
docker-compose/docker-compose.dev.yml
feed-crawler/.prettierrc
nginx/Dockerfile.dev
nginx/nginx.conf
server/.prettierrc

-   close #231
-   이전에 팀원분들께서 docker compose를 통해 개발 환경을 구축할 경우 노트북에서 작업시 발열로 인해 소음이 많이 발생한다는 피드백을 받았습니다.
- 조금이나마 자원 사용량을 덜어내기 위해 alpine 버전으로 변경하도록 했습니다.
-  기존에 nginx 사용시 debian 환경에서 동작하기에 apt-get으로 패키지를 받게 했으나 dos2unix 패키지를 받을 때 오류가 발생했었습니다.
- Docker 이미지를 빌드할 때, 네트워크 문제로 못 받아오는 건가 싶어서 다른 컴퓨터에서 확인했으나 정상적으로 설치되는 것을 확인하였습니다. 또한 프론트, 백엔드에서의 모듈은 정상적으로 설치 되기에 정확한 원인 파악이 어려웠습니다...😢
예상 원인 1. 네트워크 연결 안됨 -> 하지만, 내부에서 404 오류가 발생했기에 인터넷 연결 안됨과는 거리가 멀다고 생각했습니다.
예상 원인 2. 데비안 패키지 저장소 서버 문제 -> 다른 컴퓨터에서 진행했을 때는 정상적으로 다운되는 걸 보니 문제 없다고 판단됩니다.
예상 원인 3. 데비안 10  Buster 버전의 패키지 저장소 종료 -> 데비안 아카이브로 경로가 변경됐을 수도 있습니다. 데비안 이전 버전의 패키지들은 아카이브로 이동되기에 기존 deb.debian.org 에서 사라졌을 수도 있습니다. -> 가장 유력
[ 발생 오류 ]
```
> [nginx 3/5] RUN apt-get update && apt-get install dos2unix
Ign:1 http://deb.debian.org/debian buster InRelease …
```

📦 chore: nginx alpine 버전 변경
