boostcampwm-2024/web05-Denamu

.github/workflows/deploy.yml
server/package.json

-  비로그인 셸 버전 관리를 위한 스크립트 작성
```bash
export NVM_DIR=~/.nvm
source ~/.nvm/nvm.sh
```
Github Actions에서 ssh 접속 시, 비 정상적인 node 및 npm 버전을 사용하는 것을 발견.
이에 별도의 `NVM_DIR` 환경변수를 정의 해주는 스크립트를 추가하였습니다.

📦 chore: CD 파이프라인 nvm 환경 변수 명시

---

.cz-config.js
package-lock.json
package.json

-   close #35
-   commitizen을 사용할때, 어떤 입력을 받을지 정할 수 있다. 타입, 메세지, 메세지 바디, 이슈 내용 등. 우리는 타입, 메세지만 받아도 충분하다고 생각해서 두 가지를 받기로 했다.
-   commitizen을 적용해서 팀 전체의 commit 컨벤션을 설정하고, 이모지를 찾아서 사용하는 번거로움 해소
1. git status 상태의 파일이 있어야 한다.
2. client나 server가 아닌 web05-Denamu 디렉토리 위치여야 한다.
3. npm run commit을 입력한다.
4. 타입을 선택한다.
5. 메세지를 입력한다.
6. 엔터 끝!

📦 chore: commitizen 설정

---

package.json

- 이전 PR(#51)에서 conflict를 잘못 처리해 의존성이 이상하게 섞여버렸음
- 필요없는 의존성이 잘못 들어간 것을 확인했고 제거함
- 프로젝트 루트 폴더 내부에 있는 package.json 내 scripts 코드를 `prepare`, `commit` 이 들어가도록 수정했습니다.
- 필요 없는 의존성 (`clsx`, `tailwind-merge`) 은 제거했습니다.

♻️ refactor: dependencies 제대로 들어가지 않은 부분 수정

---

server/.gitignore
server/ecosystem.config.js
server/package.json
server/test/jest-e2e.json
server/test/jest-integration.json
server/test/jest-unit.json
server/tsconfig.json

-   close #27
-   분명 테스트 다 했다고 생각했는데, 막상 돌리니 안 돌아가는 문제가 꽤나 많았다.
- 어제 긴급 PR로 인해 어디까지 작업을 했는지 도중에 길을 잃고 커밋을 해버려서 확실한 테스트를 하지 못 하고 PR을 올렸다.
- 그래서 나만의 테스트 목록을 만들어서 이 작업들을 다 테스트 하고 커밋하고 PR을 올렸다.
---
모든 스크립트 돌려보기 ✅
- build ✅
- start ✅
- start:dev ✅
- start:debug ✅
일반 코드 import 경로 확인 ✅
테스트 코드 import ✅
- unit ✅
- e2e ✅
- integration test ✅
테스트 환경 커버리지 돌려보기 ✅
- test ✅
- e2e ✅
- unit ✅
절대 경로로 불러와지던 문제 해결 ✅
---
모든 스크립트가 실행됨을 확인했다.
-   tsconfig에서 baseUrl 옵션 때문에 계속해서 절대 경로로 불어와졌다. 하지만, test 디렉토리가 src안에 있는게 아닌 server 안에 있었기에 절대 경로로 server 디렉토리를 baseurl로 잡을 경우 test 코드 내에서 import시 상대 경로가 아닌 `src/경로` 로 시작되는 곳에서 모듈을 불러오는 문제가 있었다. 이럴 경우 test 코드 기준으로 모듈이 올바르게 import 되지 않았다.
- tsconfig에서 baseUrl을 rootDir로 변경하여 디렉토리 기준으로 상대 경로로 가져올 수 있게 바꿨다. 모든 코드가 정상적으로 동작함을 확인했다.
일반 소스 코드에서도 import 시 경로 확인, 테스트 코드에서도 import …

♻️ refactor: 테스트 환경 내부 완전 분리

---

server/src/feed/feed.entity.ts

`feed` 엔티티 속성 값 수정
feed가 처음 생성될 때 조회수를 0으로 설정하는 default value가 누락되었음을 확인하여 설정 처리 하였습니다.

🐛 fix: feed entity viewcount 기본값 설정

---

.github/workflows/deploy.yml
ecosystem.config.js
rss-notifier/package-lock.json
rss-notifier/package.json

`deploy.yml` 오탈자 수정 및 의존성 추가
rss-notifier에 개발 의존성으로 `typescript` 를 추가하였습니다.
기존에 개발환경에서는 typescript가 global하게 설치되어 있던 터라, 이 부분을 놓쳤네요 😓

🐛 fix: rss-notifier 배포 스크립트 오탈자 및 의존성 추가

---

server/.eslintrc.js

`IntelliJ` IDE에서 이유는 모르겠지만 엔드라인 시퀀스 관련 lint 오류가 계속 떴습니다.
```javascript
'prettier/prettier': [
'error',
{
endOfLine: 'auto',
},
],
```
해당 문제를 제거해주는 옵션을 lint 설정 파일에 추가하였습니다.

💄 style: eslint eof 오토 설정 추가

---

server/src/admin/admin.controller.ts
server/src/admin/admin.entity.ts
server/src/admin/admin.service.ts
server/src/blog/blog.entity.ts
server/src/common/guard/auth.guard.ts
server/src/feed/feed.repository.ts
server/src/feed/feed.service.ts
server/src/rss/rss.api-docs.ts
server/src/rss/rss.controller.ts
server/src/rss/rss.entity.ts

HTTP 요청에서 쿠키로 전달된 `sessionId`를 Redis를 통해 검증하여 사용자를 인증하는 `CookieAuthGuard`를 작성했습니다.
`쿠키가 없는경우` && `전달된 쿠키의 sid가 redis에 존재하지 않는경우(즉, 만료된 경우)` 에 `UnauthorizedException` 이 반환됩니다.
사전에 백엔드 팀에서 논의된대로, `import type`은 사용하지 않기로 하고 일괄 제거 처리 하였습니다.
> **사용하지 않는 이유**
**TypeScript에서 import type 구문은 타입 전용으로만 선언을 가져올 때 사용됩니다.** 
이를 통해 컴파일러는 가져온 선언이 런타임에 영향을 미치지 않는다는 것을 보장합니다. 하지만 이 방식에는 몇 가지 문제점이 있어, 프로젝트에서는 import type을 사용하지 않기로 결정했습니다.
1. import type의 문제점
`import type`은 오직 타입 정보를 위해 존재합니다. 따라서 TypeScript 컴파일 후 JavaScript로 변환될 때, 실제로 런타임에 필요한 객체나 모듈은 포함되지 않지만, 실제로 컴파일 단계에서 에러가 발생하지 않습니다.
2. 개발자 실수로 인한 런타임 에러의 발생 가능성
이렇게 _"개발자가 실수로 런타임 에러를 발생시킬수 있는 환경이 된다."_ 라는 것 자체가 매우 치명적으로 다가왔고, 이는 제거해야하는 부분이라고 생각했습니다.
- cookie가 없는채로 요청 시

✨ feat: Cookie 기반 인가 Guard 작성

---

client/.gitignore
client/src/api/instance.ts
client/src/api/queries/rssApi.ts
client/src/components/RssRegistration/RssRegistrationModal.tsx
client/src/components/RssRegistration/RssValidation.ts
client/src/hooks/useRegisterRss.ts
client/src/types/rss.ts

-   close #107
- 각 블로그 마다 RSS URL양식이 달라서 어떤 식으로 유효성 검사를 진행해야할지 고민했습니다.
- 서버측에서 검증을 한번 더 하고 관리자가 승인/거절 하는 방식이라 클라이언트에서 크게 검사를 진행할 필요가 없음
- 클라이언트측에서는 https:// 식의 기본적인 URL양식인지만 검사 하는것으로 구현함
- RSS 등록 API 연동

✨ feat: RSS등록 API 연동

---

server/src/main.ts

- cors 클라이언트 도메인 추가
`https://denamu.shop` 도메인을 cors 허용처리 하였습니다.

🐛 fix: 새롭게 등록된 도메인 cors 설정 추가

---

server/src/common/filters/http-exception.filter.ts
server/src/feed/feed.api-docs.ts
server/src/feed/feed.controller.ts
server/src/feed/feed.entity.ts
server/src/feed/feed.repository.ts
server/src/feed/feed.service.ts
server/test/feed/trend.e2e-spec.ts

-   close #18
- 팀 내에서 지금 당장 게시글 제거에 대해서는 고려 안 했기에 구체적인 구현은 하지 않았다.
- 지금 당장에는 만약 Redis 테이블의 상위 4개에 대응하는 게시글이 없다면 상위 2개만 반환하는 식으로 구현했다.
-   테스터 픽스처를 사용할 경우 테스트끼리의 독립성이 떨어진다. 하지만 E2E 테스트 같은 경우 매번 같은 상황에서 여러 동작을 하는 테스트가 있다.
- 테스트 픽스처를 올바르게 사용하는 방법에 대해 학습이 필요할 것 같다.
- 참고 자료: https://jojoldu.tistory.com/611
-  트랜드 게시글 4개 추출 API 구현 (최초 홈페이지 로드용)
- 트랜드 게시글 4개 추출 API 테스트 코드 작성 (게시글 제거 상황 제외)
- API 명세 작업

✨ feat: 트랜드 게시글 4개 추출 API 구현

---

server/src/common/logger/logger.interceptor.ts

-   close #96
-  클라이언트 접근 방식이 Cloudflare 접근 -> netlify로 접근하다 보니, 백엔드에서 클라이언트 IP를 로깅했을 때 Cloudflare IP로 통일되어 들어오는 문제가 있었다.
- 박무성 캠퍼가 조회수 API 구현 중 Cloudflare의 Proxy Header를 뽑아내는 방법을 찾아내서 적용했다.
-   실제 클라이언트 IP 로깅
- 실제 IP가 첨부되기에 생략

🐛 fix: cloudflare IP만 뜨던 문제 수정, 실제 클라이언트 IP 로깅

---

rss-notifier/package-lock.json
rss-notifier/package.json
rss-notifier/src/db-access.ts
rss-notifier/src/rss-notifier.ts

-   close #152
- 먼저 Velog의 RSS와 다른 블로그의 RSS를 비교 했는데 차이점이 없었습니다.
- 고민하며 로그를 확인하니 글이 여러 개인 경우는 배열을 반환하지만 글이 한 개인 경우에는 JSON 하나만 반환하는 것을 확인했습니다.
- 블로그 서비스별로 차이가 있는 것이 아니라 1개와 여러 개의 차이점임을 발견하고 배열인지 아닌지 확인하는 로직을 추가하여 해결했습니다.
- 벌크 삽입을 사용하면 1개의 데이터만 실패해도 다른 모든 데이터가 삽입되지 않는 단점이 있었습니다.
- 이것을 보완하기 위해 단일 삽입을 병렬적으로 시도하는 방법으로 수정했습니다. 
- 이 때, Promise.all을 사용했지만 각각의 결과를 알기가 어려웠습니다.
- 찾아보니 Promise.allSettled라는 함수를 사용하면 이 부분을 처리할 수 있음을 확인했습니다.
- 글이 하나인 블로그도 지원하도록 수정
- createdAt으로 정렬 후 Feed 테이블에 데이터를 삽입
- Feed 삽입 시 다른 트랜잭션으로 처리하여 하나가 실패해도 다른 Feed에 영향이 가지 않도록 수정
- 인코딩된 URL을 한글로 디코딩 후 저장
- 생성순으로 정렬되어 삽입함을 확인
- `"`, `&` 등 모두 unescape된 상태로 저장됨을 확인
- URL의 한글이 모두 디코딩되어 있는 것을 확인

🐛 fix: RSS 관리 파이프라인 개선 및 버그 수정

---

client/src/components/chat/layout/ChatFooter.tsx
client/src/components/sections/AnimatedPostGrid.tsx
client/src/components/sections/TrendingSection.tsx

-   close #123 
- 트렌딩 포스트 애니메이션 기능 추가
- PostCardGrid를 AnimatedPostGrid로 교체
- framer-motion으로 순위 변경 시 애니메이션 구현
- 순위 상승 시 시각적 피드백 추가 (파란색 테두리, 그림자 효과)
- 애니메이션 구현 사항
- useEffect와 useState를 사용해 이전 포지션 추적
- AnimatePresence로 부드러운 진입/퇴장 처리
- spring 애니메이션으로 자연스러운 움직임 구현
- 순위 상승 시 z-index 조정으로 자연스럽게 겹쳐지도록 표현
https://github.com/user-attachments/assets/2219e0b9-34e7-43ba-a693-7fd57d70bb0b
https://github.com/user-attachments/assets/98e22c56-28a0-4d77-8de2-8d3b91ae692f

✨ feat: 트렌딩 포스트 순위 변경 시 위치가 바뀌는 애니메이션 구현

---

server/src/feed/feed.controller.ts

-  #20
- GET 요청으로 조회수를 업데이트하는 것이 어색하다는 의견이 있었습니다.
- 저도 듣고 보니 업데이트에 대한 요청으로 GET이 어색하다는 생각이 들었고
POST, PATCH, PUT 3가지 메서드 중 무엇을 사용할지 고민했습니다.
- 그 중에서 POST를 사용했는데 그 이유는 클라이언트가 상태를 인지할 수 있나, 없나를 판단하는 것에서 찾을 수 있었습니다.
- 클라이언트가 현재 조회수 값을 모르고 조회수 증가 이벤트를 생성한다고 볼 수 있었고 매번 새로운 상태가 만들어집니다. 
(위 내용을 찾아보며 멱등성에 대한 개념도 새롭게 알 수 있었습니다.)
-  조회수 업데이트 API의 메서드를 POST로 수정

♻️ refactor: 조회수 증가 API의 메서드를 Post 방식으로 변경

---

client/src/components/layout/Header.tsx

-   close #171
- 로고가 작다는 피드백 반영을 위해 로고 크기 3.5rem으로 조정
- h-14 Tailwind 클래스 사용
- 로고 이미지의 height를 3.5rem(h-14)로 설정
- 기존 cursor-pointer 및 onClick 이벤트 유지

♻️ refactor: 메인 페이지 로고 사이즈 변경

---

client/src/components/sections/AnimatedPostGrid.tsx
client/src/hooks/common/usePositionTracking.ts

-   close #180
- AnimatedPostGrid 컴포넌트의 복잡한 포지션 트래킹 로직을 별도의 커스텀 훅으로 분리
- 기존에 순위 변경 시 나타나는 파란색 border 스타일 제거
- usePositionTracking 훅 생성

♻️ refactor: 순위 변경 시 나타나는 파란색 border 삭제 및 usePositionTracking 분리

---

client/src/components/common/Card/PostCard.tsx
client/src/components/common/Card/PostCardContent.tsx
client/src/components/common/Card/PostCardImage.tsx

- close #179 
- 트렌딩 포스트와 최신 포스트 섹션에서 PostCard 크기가 서로 다르게 표시됨
- 제목 길이에 따라 카드 크기가 변하는 문제 발생
- CSS Grid와 Motion의 레이아웃 처리 방식 차이로 인한 불일치
- PostCard 컴포넌트에 고정 높이를 적용해 크기 통일
- 이미지와 컨텐츠 영역의 크기를 제한해 일관된 레이아웃 유지
자세한 내용은 아래 노션 문서 참고
https://balsam-barometer-716.notion.site/Ellipsis-PostCard-UX-148e624056ec80109642e520b3082ed4?pvs=4
- PostCard 컴포넌트
- 전체 높이를 240px로 고정
- flex-col 레이아웃 유지
- PostCardImage 컴포넌트
- 이미지 영역 높이를 120px로 고정
- aspect-ratio 제거 및 overflow 처리
- PostCardContent 컴포넌트
- 제목 영역 40px 고정 높이 설정
- 제목 두 줄, 작성자 이름 한 줄로 제한
- 텍스트 크기 조정

♻️ refactor: 카드 크기 일관성을 위한 Ellipsis 처리 및 고정 높이 설정

---

server/src/admin/admin.api-docs.ts
server/src/admin/admin.controller.ts
server/src/common/guard/auth.guard.ts

- #169
- 기존에는 어드민 계정을 생성 후 빠르게 deprecated 시킬 계획이었으나 API를 살려놓는 방향으로 수정되었습니다.
- 그에 따라 어드민 계정 생성 API에 아무나 접근하지 못하도록 Guard를 적용시켜서 기존 어드민이 로그인했을 때만 접근할 수 있도록 수정했습니다.

🐛 fix: 어드민 계정 생성 시 기존 어드민 계정 로그인 시에만 생성할 수 있도록 가드 적용

---

client/src/components/sections/LatestSection.tsx
client/src/components/sections/TrendingSection.tsx

-   close #172
- TrendingSection의 시각적 계층 구조를 개선하기 위해 균일한 그림자 적용
- 기존의 단방향 그림자는 디자인의 깊이감을 제대로 표현하지 못 해 boxShadow 스타일을 사용, 원하는 방향으로 그림자 제어가 가능하도록 함
- TrendingSection
- boxShadow: '0 0 15px rgba(0, 0, 0, 0.1)' 적용
- 균일한 그림자 적용
- LatestSection
- 점선 테두리 제거
- 기본 rounded-lg 스타일 유지

♻️ refactor: 트렌딩 포스트 점선을 그림자로 변경, 최신 포스트 점선 제거

---

server/src/admin/admin.api-docs.ts
server/src/admin/admin.controller.ts

- #169
- 어드민 페이지 출력 시 세션 아이디를 검증하기 위한 API를 추가했습니다.
- 명기님과 이야기를 나눈 결과, 가드가 설정되어 있어 어드민 페이지에서 아무 작업도 할 수 없지만 어드민 페이지 랜더링도 막아야 할 것 같다고 의견이 합쳐졌습니다.
- 그래서 새로고침 등 요청을 보낼 때 세션아이디를 검증할 수 있는 API를 추가했습니다.
- 그 이외에도 adminService를 loginService라고 표기한 파트가 있어 수정을 했습니다.
- API에 swagger를 적용시켜 명세를 확인할 수 있도록 작성했습니다.
- 첫 번째 스크린 샷은 정상적으로 로그인하고 sessionId가 유요한 경우입니다.
- 두 번째 부터는 틀린 sessionId로 설정했을 때 응답입니다.

✨ feat: 어드민 페이지 출력 시 세션 아이디를 검증하기 위한 API 추가

---

client/src/components/RssRegistration/FormInput.tsx
client/src/components/RssRegistration/RssRegistrationModal.tsx
client/src/components/chat/ChatButton.tsx
client/src/components/chat/layout/ChatFooter.tsx
client/src/components/chat/layout/ChatHeader.tsx
client/src/components/layout/Header.tsx
client/src/components/search/SearchButton.tsx
client/src/components/sections/TrendingSection.tsx
client/src/index.css

-   close #173 
- Header, 버튼 등 주요 UI 요소들에 primary 색상(#27ae60) 적용
- NavigationMenu 관련 컴포넌트(ChatButton, SearchButton)에는 hover 시 primary 색상이 적용되도록 구현
- 모바일 메뉴의 경우에도 동일한 색상 시스템 적용하여 일관성 유지
- shadcn/ui의 기본 테마에서 link hover시 primary 색상을 사용하는 문제 발견
- 일반 링크와 NavigationMenu 링크를 구분해 스타일 적용
- 클래스 명시를 통해 의도한 컴포넌트에만 primary 색상이 적용되도록 수정
1. global.css 수정
- primary 색상을 HSL 값(145 63% 42%)으로 설정
2. Header 컴포넌트 수정
- border 색상을 primary/20으로 변경
- 로그인, 블로그 등록 버튼에 primary 색상 적용
- 모바일 메뉴 관련 요소들에 primary 색상 적용
3. NavigationMenu 컴포넌트 수정
- ChatButton, SearchButton에 hover 시 텍스트 색상 및 배경색 변경 로직 추가
https://github.com/user-attachments/assets/88af5b45-c880-4591-aba5-cd91f627afd4

♻️ refactor: 메인 페이지 Header 버튼 primary로 변경

---

client/src/api/instance.ts
client/src/hooks/queries/useTrendingPosts.ts
client/src/store/useChatStore.ts
server/src/main.ts

-   close #199 
- CloudFlare 및 Netlify에 denamu.site 설정
- FE, BE 기존 도메인 변수 변경
`instance.ts` : axios에 사용되는 baseURL을 수정하였습니다.
`useTrendingPosts.ts` : sse 커넥션에 활용되는 URL을 변경하였습니다.
`useChatStore.ts` : web socket 커넥션에 사용되는 http hand-shake URL을 변경하였습니다.
`main.ts` : NestJS의 CORS 허용 URL을 변경하였습니다.

📦 chore: 도메인 이전에 따른 경로 변수 변경

---

server/src/chat/chat.gateway.ts

-   close #195 
- 웹소켓 채팅서버 최대 커넥션 수 제한
[4주차 스프린트 리뷰회의](https://balsam-barometer-716.notion.site/Week-4-09a81378938f43399603575ec409f506?pvs=4)에서 발의된 안건을 반영하기 위해 웹소켓 서버에서 `handleConnection` 을 수행할 때 서버의 커넥션 수를 확인하고, 500명 이상이면 아래와 같은 이벤트를 connection을 요청한 클라이언트에게 반환합니다.
`error`, `message: '채팅 서버의 한계에 도달했습니다. 잠시후 재시도 해주세요.'`

⚡️ perf: 서버 안정성 향상을 위한 채팅 서버 최대 사용자 제한 추가

---

server/src/admin/admin.controller.ts
server/src/admin/admin.service.ts
server/src/common/guard/auth.guard.ts
server/test/statistic/today.e2e-spec.ts

PR 작성자가 로그인 뚫고 작성자가 고침
-   close #58
-   Login Guard 코드를 자세히 보다가 이상한 점을 발견했다.
```typescript
const loginId = await this.redisService.redisClient.get(sid);
if (!loginId) {
throw new UnauthorizedException('인증되지 않은 요청입니다.');
}
```
- 위 코드로 구현이 되어있을 경우, Redis에 string 값을 가지는 키가 있다면, 쿠키에 그 Redis string 값에 대한 키를 대입할 경우 관리자 권한이 뚫릴 것 같았다.
- 실제로 해보니 뚫렸다.
- prefix로 로그인 서비스, CookieAuthGuards에 `login:` 도메인을 추가하여 해결하였다.
- Redis에서 도메인의 중요성을 느꼈다.
-   관리자 계정이 중복 로그인이 되어야 할지 의문을 가졌다.
- 관리자 계정은 혹여나 임시 PC에 로그인했을 때, 로그아웃을 안 하고 다른 곳에서 로그인 한다면 임시 PC에 쿠키가 남아있어 치명적으로 다가올 수 있기에 중복 로그인 기능을 막았다.
- 이때, key = login:{sid}, value = {관리자ID} 라서, 관리자 ID에 대응하는 키를 찾아야했는데, 이러면 풀스캔을 해야한다.
- 관리자 같은 경우 계정이 많지 않아서 속도상 큰 문제가 되지 않을 거라 생각했다.
- 그리고 100개씩 가져오게 하면 Redis의 부하를 줄일 수 있기에 100개씩 세션을 가져와서 검사하게 했다.
- Guard Redis login Prefix 추가 …

🐛 fix: 쿠키 Redis String Key 일 경우 Login 보안 버그 수정

---

server/src/admin/admin.api-docs.ts
server/src/admin/admin.controller.ts
server/src/admin/admin.service.ts

> [!IMPORTANT]
> @asn6878님께서 테스트 코드를 많이 개편중이셔서 본 PR에 테스트 코드는 작성하지 않았습니다.
-   close #222
-   httpOnly로 설정된 세션 쿠키라 백엔드에서 지워줘야해서 maxAge 0으로 응답하여 바로 만료되게 구현했다.
-   로그아웃 swagger 구현
- 로그아웃 Notion API 명세서 작성
- 로그아웃 API 구현
- swagger
- postman
- postman (쿠키 지워짐)
- redis

✨ feat: logout API 구현

---

.github/workflows/deploy.yml
rss-notifier/package-lock.json
rss-notifier/package.json
rss-notifier/src/db-access.ts
rss-notifier/src/rss-notifier.ts
server/src/common/redis/redis.constant.ts
server/src/feed/feed.api-docs.ts
server/src/feed/feed.controller.ts
server/src/feed/feed.service.ts

-   close #203
- keys 명령이 실행되는 도중에는 Redis의 모든 명령을 블로킹합니다.
- 현재는 데이터가 몇 개 없어서 keys를 사용해도 큰 문제는 없지만 O(N)의 시간 복잡도라도 1만개, 10만개 등 늘어나면 성능 이슈가 발생할 수 있습니다.
- 추후에 성능 이슈가 발생한다면 `SCAN`으로 방법을 바꿀 수 있을 것 같습니다.
- 저는 SCAN을 사용하진 않았지만 `feed:recent`라는 key를 두어 recent 피드가 존재하는지 파악할 수 있도록 해놓았습니다.
- (PR을 작성하면서 생각해보니, 객체를 직렬화해서 List 하나에만 담아두는 것이 더 좋은 방법일 것 같습니다.)
- 처음에는 Redis 공식 문서에 있던 Node-redis를 사용했으나 Hash 데이터를 저장할 때 알 수 없는 에러가 발생했습니다.
- 혹시나 싶어 ioredis로 변경하니 기존 코드를 거의 수정하지 않고 에러 없이 사용할 수 있었습니다.
- 정보를 좀 더 찾아보니 Node-redis는 직렬화에 있어서 엄격한 편이고 ioredis는 유연하게 처리한다고 합니다.
- 처음에는 블로그에서 바로 가져온 데이터를 Redis에 저장하고 프론트에 전송할 생각이었습니다.
- 다만 이렇게 하면 blogPlatform 데이터나 author 데이터를 가져올 수 없는 문제가 생겼습니다.
- 그래서 DB에 저장되어던 가장 최근 피드의 ID를 구해서 새로 업데이트된 피드 ID를 계산했습니다.
- 피드를 저장하고 가지고 있던 ID를 활용해서 `rss_accept` 테이블과 JOIN 연산을 진행했습니다.
- 결과적으로 추가적인 …

✨ feat: 최신 게시글 실시간 업데이트 API 구현 

---

server/test/fixture/feed.fixture.ts
server/test/statistic/dto/statistic-query.dto.spec.ts
server/test/statistic/today.e2e-spec.ts

-   close #162
- 입력 값에 대해서 E2E 테스트를 하는 게 맞을까? 싶었다.
-  팀내에서 입력값에 대해서는 DTO 테스트로 별도 분리하자는 의견이 나와서 이 의견에 따르기로 했다.
-   rssAccept Fixture 속성 이름 변경
- dto 테스트 분리
- today 테스트 이름들 컨벤션에 맞추기
- today 테스트 given, when, then 패턴 적용

✅ test: Today Statistic Test 작성

---

server/test/statistic/all.e2e-spec.ts
server/test/statistic/today.e2e-spec.ts

-   close #204
-   InMemory DB 1회 접근 방식으로 변경
- dto 테스트 분리
- 테스트 데이터 개수, 범위 축소
- 일일 통계 API의 DTO 검증과 동일한 DTO라 테스트 3개가 줄었습니다.

✅ test: 전체 통계 API 테스트 코드 작성

---

server/test/rss/history/accept.e2e-spec.ts
server/test/rss/history/reject.e2e-spec.ts

-   close #154
-  RSS 승인 기록 조회 API 테스트 코드 작성
- RSS 거절 기록 조회 API 테스트 코드 작성

✅ test: RSS 승인/거절 기록 API 테스트 코드 작성

---

server/src/rss/rss.service.ts

-   #205
-  rss url 형태를 사용하는 것이 문제였습니다.
- velog는 `@ID`형태가 아니어도 RSS를 불러올 수 있어서 버그가 발생했습니다.
- 어차피 관리자가 RSS의 유효성을 검사한다고 생각하여 velog, medium 등 블로그 플랫폼만 구별할 수 있도록 수정했습니다.
- 예시 스크린 샷
- rss_accept 테이블에 들어가는 값 확인

🐛 fix: velog rssurl 등록 시 '@'가 없으면 etc로 분류되는 버그 수정

---

server/src/rss/rss.controller.ts
server/src/rss/rss.service.ts

-   close #260
- Swagger 네이밍에 맞춰서 컨트롤러, 서비스 메소드 명 변경
- Controller, Serivce 함수명 컨벤션 정해서 통일하기
- 동작 Prefix + 도메인 이름
- 동사가 앞에
- 조회 : read
- 쓰기 : create
- 수정 : update
- 제거 : delete
- 그 외 : 직접 작성
- Controller, Service 명은 동일하게 맞추기
-   동작 Prefix + 도메인 이름으로 변경

🧼 clean: 네이밍 컨벤션 수정

---

server/src/feed/dto/search-feed.dto.ts
server/test/feed/dto/query-search.dto.spec.ts

-   close #16
-   현재 테스트 DB가 Sqlite InMemory DB이기에 MySQL에 있는 Full Text Index Search를 사용할 수 없다.
- 최소한 DTO 테스트라도 해야할 것 같아서 작성했다.
- 최소 수 검증 기능 추가
-   Search Request DTO 테스트

✅ test: search dto 테스트 코드 작성

---

client/src/components/common/Card/PostCardSkeleton.tsx
client/src/components/sections/LatestSection.tsx
client/src/components/sections/TrendingSection.tsx

-   close #270
- 데이터 로딩 중에 빈 화면이 보이는 것은 사용자 경험을 저하시킬 수 있음
- LoadingIndicator만으로는 실제 로드될 컨텐츠의 구조를 미리 파악하기 어려움
- 데이터 로딩 시 PostCard 이외의 컴포넌트에서 움직임 발생
- shadcn/ui의 Skeleton 컴포넌트 활용으로 디자인 시스템 일관성 유지
- 무한 스크롤의 부드러운 경험을 위한 Intersection Observer 최적화
- threshold: 0.3, rootMargin: "100px"로 설정해 비교적 빨리 로딩할 수 있도록 함
- 데이터 로딩 상태에 따른 레이아웃 유지를 위한 최소 높이 설정
- PostCardSkeleton 컴포넌트 구현
- shadcn/ui Skeleton 컴포넌트 활용
- 실제 PostCard와 동일한 레이아웃 구성
- 반응형 그리드 레이아웃 적용
- 최신 포스트 섹션(LatestSection) Skeleton UI 적용
- 초기 로딩 및 무한 스크롤 시 Skeleton UI 구현
- Intersection Observer 설정 최적화
- 추가 로딩 시 Skeleton UI 자연스러운 전환
- 트렌딩 포스트 섹션(TrendingSection) Skeleton UI 적용
- 초기 로딩 상태 Skeleton UI 구현
- 데이터 로딩 상태 처리 로직 개선
https://github.com/user-attachments/assets/3f6326b5-5322-498e-98cd-a7cf4cc02213 …

✨ feat: PostCard 로드될 때 Skeleton UI 적용

---

server/src/feed/feed.controller.ts
server/src/feed/feed.service.ts

-   #261
-  타입을 명시하지 않은 부분을 찾아서 타입을 붙였습니다.
- 그 과정에서 controller에서 header로부터 정보를 추출하던 부분을 모두 service 레이어로 옮겼습니다.
- ip 같은 경우, `string | string[]` 타입을 반환하기에 타입 가드를 하나 생성하여 string일 때만 사용할 수 있도록 했습니다.

🧼 clean: type을 추론할 수 없는 부분 찾아서 타입 명시

---

.gitignore
loadtest/BE_loadtest.json
loadtest/FE_loadtest.json
package-lock.json
package.json

-   close #164
artillery, k6, locust
-  locust 스크립트 작성 방법: Python 언어 기반이다.
- k6 스크립트 작성 방법: JS 언어 기반이다.
- artillery 스크립트 작성 방법: yaml, json 기반이다.
- artillery가 가장 간단하게 스크립트를 작성할 수 있고 간단하게 테스트 가능하다.
- 부하 테스트를 위한 새로운 서버 인스턴스를 구축하여 동일 사양으로 테스트 인스턴스를 만들 경우 인스턴스에 관련된 추가적인 비용이 발생할 수 있고, 높은 트래픽으로 인한 네트워크 비용이 발생할 수 있다고 판단해서, 실제 클라우드에 테스트를 하는 것은 올바르지 않다고 판단했다.
- 부하 테스트를 실제 인스턴스에 했다가 과금이 되었다는 사례도 봤었다 보니, 본 방법은 더 올바르지 않다고 생각했다.
- 로컬에 Oracle VM Ware를 사용하여 서버와 동일한 사양으로 2코어 4GB RAM의 staging 서버(가상 머신)을 구축하여 서버 코드를 복사하여 테스트를 하려고 합니다. 하지만, 이럴 경우 클라우드 환경의 네트워크, CPU, RAM 속도와 100% 동일한 환경을 갖추기는 어렵다고 생각했습니다. 프로세서 수, RAM 용량은 맞출 수 있다만 그 외적인 클럭 속도, 네트워크 대역폭 등은 못 맞출 것 같다.
- Oracle VM Ware 가상 머신 구축
-  BE 부하 테스트 시나리오 작성
- FE 부하 테스트 시나리오 작성
- BE 부하 테스트 package.json 작성
-  FE 부하 테스트 package.json 작성

✅ test: 부하 테스트 작성

---

rss-notifier/src/rss-notifier.ts

-   close #23
- 썸네일 경로가 상대 경로일 경우, 그대로 저장하는 문제가 있었다.
- 이 문제 같은 경우 우리 서비스로 가져오면 우리 도메인의 경로로 썸네일을 요청하기에 썸네일 소스가 존재하지 않았다.
- 원본 블로그 경로에 요청을 보내야했는데, 블로그 게시글의 썸네일 경로를 저장할 때, 블로그 경로와 디렉토리 경로를 합쳐 한 번에 저장하면 된다고 생각했다.
- 원본 블로그 도메인에 디렉토리 경로를 합쳐 요청을 하면 이미지가 불러와짐을 확인하여 이대로 구현을 진행했다.
-   블로그 게시글 HTML에 og:image 태그의 썸네일 이미지가 상대 경로일 경우 게시글의 썸네일을 데나무 서비스에서 로드할 수 없는 문제 발생
- 마지막 행이 썸네일 경로 행이다.
- 몇몇 블로그에서 썸네일 경로가 상대 경로로 `/assets/img/logo.png` 로 저장되는 문제가 있었다.
- 앞에 도메인을 붙여서 저장함으로써 이미지를 불러올 수 있도록 문제를 해결했다.

🐛 fix: 블로그 썸네일 상대 경로 문제 해결

---

.github/workflows/deploy_client.yml
.github/workflows/deploy_server.yml
client/src/api/instance.ts
client/src/components/about/HeroSection.tsx
client/src/components/common/Card/PostCardContent.tsx
client/src/hooks/queries/useTrendingPosts.ts
client/src/store/useChatStore.ts
nginx.conf
server/src/common/email/mail_content.ts

프로젝트 내에서 nginx 설정을 하고, 직관적으로 관리할 수 있도록 루트 디렉토리 내에 nginx 설정 파일을 만들었습니다.
그 후, `/etc/nginx` 경로 내에서 루트 디렉토리의 conf 파일을 include 처리 해 주었습니다.
```
http {
...
include /var/web05-Denamu/nginx.conf;
}
```
기존에 Netlify에서 반환하던 정적파일을 NGINX에서 반환할 수 있도록 라우팅 처리 해두었습니다.
```
location / {
root /var/web05-Denamu/client/dist;
index index.html;  # 기본 파일 설정
try_files $uri /index.html;  # SPA 지원
}
location /files {
alias /var/web05-Denamu/static/;
try_files $uri $uri/ =404; # 파일이 없으면 404 반환
}
...
```
`/` 루트 경로로 들어오는 요청들은 client/dist 내 파일들(index.html, css 및 다양한 js 파일들)을 반환합니다. 
현재 https://www.api.denamu.site/ 경로로 접속해보시면, public-was 인스턴스에서 FE 정적파일들을 반환해주는 상태임을 확인하실 수 있으며, React Route 역시 정상적으로 동작하는 것을 보실 수 있습니다.
> [!IMPORTANT]
> @jungmyunggi @junyeokk baseURL 변경 내용 확인하시기 바랍니다.
public-was 인스턴스 서버로 가는 요청은 기존에 `A 레코드`를 …

📦 chore: Netlify 종속성 제거를 위한 NGINX 설정 변경 및 FE CD 스크립트 작성

---

server/src/feed/feed.service.ts

- close #19
- netlify, cloudeflare 등의 외부 의존성을 제거함에 따라서 QUIC 에러를 고려하지 않아도 됨
- 이에 따라서 강제 이벤트 발생을 삭제할 필요성을 확인
- rxjs
- lodash
- eventsource
- SSE
- [테오님 블로그, Rxjs](https://velog.io/@teo/rxjs)
- [Nest.js SSE 공식문서](https://docs.nestjs.com/techniques/server-sent-events)
- [Event Source API](https://developer.mozilla.org/en-US/docs/Web/API/EventSource)
- [김용성님 블로그, lodash 소개](https://velog.io/@kysung95/%EC%A7%A4%EB%A7%89%EA%B8%80-lodash-%EC%95%8C%EA%B3%A0-%EC%93%B0%EC%9E%90)
- 피드 순위 변경이 생길 경우에만 이벤트가 발생하도록 수정
- 조회수 업데이트 전
- 조회수 업데이트 후

⚡️ perf: 피드 순위 변동이 생길 경우에만 이벤트가 발생하도록 수정

---

nginx.conf
server/src/main.ts

- close #299 
> 본 PR 이후부터는 더 이상 CloudFlare를 사용하지 않습니다.
기존에 동작중이던 CloudFlare 서비스를 삭제하였습니다.
또한, 가비아의 DNS 포워딩 설정을 아래와 같이 처리하였습니다.
서버 인스턴스 내에 `certbot`, `python3-certbot-nginx` 를 설치하였습니다.
```bash
$ sudo apt-get install certbot
$ apt-get install python3-certbot-nginx
```
HTTP 요청을 HTTPS로 리다이렉션 처리하였으며, 인증서 발급을 위한 키페어 경로를 선언해주었습니다. (SSL 인증서 발급 명령어 치면 알아서 추가됩니다.)
Let's Encrypt에서 발행해주는 DV(Domain Validation)은 90일을 주기로 만료됩니다. (인증서 보안 강화를 위해)
**이에 따라 만료되기 이전에 자동으로 인증서를 재발급 받는 과정이 필요합니다.**
서버 인스턴스에 crontab을 설정하였습니다. 서버에 접속 후 `sudo crontab -l` 입력시
`0 18 1 * * sudo certbot renew --pre-hook "sudo systemctl stop nginx" --post-hook "sudo systemctl restart nginx"` 이 추가되었음을 보실 수 있습니다.
해당 명령은 매월 1일 새벽 3시에 sudo certbot renew 명령어를 통해 인증서 재발급을 수행하며, 명령어를 실행 전과 후로 nginx를 멈추었다가 재실행 합니다. (갱신 시 nginx 서비스를 중단해야 하기에 잠시 …

📦 chore: Let's Encrypt SSL/TLS 인증서 발급 및 Nginx 설정 추가

---

nginx.conf

nginx는 기본값으로 SSE Connection이 60초이상 아무런 데이터가 오지 않을 시 연결을 끊어버립니다.
이 기본값을 3600초로 수정하였습니다.

🐛 fix: nginx proxy_read_timeout 1시간으로 설정

---

client/index.html
client/public/robots.txt

-   close #302 
- meta tag추가
```
<meta name="description" content="개발자들의 블로그허브 데나무" />
<meta name="keywords" content="블로그, 개발자, 데나무, 개발, 개발 블로그, 개발 허브" />
<meta property="og:title" content="Denamu" />
<meta property="og:description" content="개발자들의 블로그 허브 데나무" />
<meta property="og:image" content="src/assets/logo-denamu-title.svg" />
<meta property="og:url" content="https://your-website-url.com" />
<meta property="og:type" content="website" />
```
- 글꼴 preload
```
<link
rel="preload"
as="style"
href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.8/dist/web/variable/pretendardvariable.css"
/>
<link
rel="stylesheet"
href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.8/dist/web/variable/pretendardvariable.css"
/>
```
- robots.txt추가

⚡️ perf: SEO 메타태그 및 robots.txt 추가

---

nginx.conf
server/src/chat/chat.gateway.ts
server/src/common/logger/logger.interceptor.ts
server/src/feed/feed.service.ts

-   close #300 
```
location /api {
...
proxy_set_header Host $host; # Host 헤더로 host 변수값 전달
proxy_set_header X-Real-IP $remote_addr;  # X-Real-IP 헤더로 실제 IP 전달
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # X-Forwarded-For 헤더로 실제 IP 전달
proxy_set_header X-Forwarded-Proto $scheme; # 클라이언트의 프로토콜 전달
}
...
```
https://developer.mozilla.org/ko/docs/Web/HTTP/Headers/X-Forwarded-For
- **`X-Real-IP` 헤더** : 클라이언트의 실제 IP 주소를 **단일 값으로 전달** 하는 헤더. 프록시 서버가 실제 IP를 백엔드 서버에 전달하는 용도로 주로 사용됨. (의미상으로는 _바로 직전의 IP 주소_ 가 맞는거 같긴한데, 이건 표준은 아닌 것 같아서 일단 이렇게 설정해두었습니다. 😅)
- **`X-Forwarded-For` 헤더** : 클라이언트의 IP 주소뿐만 아니라 **요청이 거쳐온 모든 프록시 서버의 IP 주소를 목록 형식으로 전달**하는 헤더. 
> 예시 
클라이언트 : `1.2.3.4`, 리버스 프록시 서버 : `127.0.0.1` 일때, `X-Forwarded-For` 헤더 값은 `1.2.3.4, 127.0.0.1`이 됨.
- **`X-Forwarded-Proto` 헤더** : …

🐛 fix: Nginx Forwarded-IP 전달 설정 및 채팅 날짜 알림 로직 수정

---

server/src/chat/chat.gateway.ts
server/src/chat/chat.module.ts

-   close #280 
기존의 `node-cron`에서 `@nestjs/schedule` 으로 변경하며 실행이 되지 않았습니다.
이에 따라 모듈 설정에 임포트를 추가하였습니다.

🐛 fix: 채팅 자정 Cron 동작을 위한 ScheduleModule 임포트

---

docker-compose/docker-compose.dev.yml
docker-compose/docker-compose.local.yml
docker-compose/docker-compose.prod.yml

-   close #326
-   close #327
-   기본 컨테이너의 시간대는 UTC 기준이다. 하지만, 우리는 KST 기준으로 돌려야 하기에 환경 변수 TZ를 넣도록 구현했다.
- 로그 찍히는 시간대가 KST가 아니라 UTC라서 기존 로그와 섞이는 문제가 있었다.
-   환경변수로 컨테이너 시간대 변경

📦 chore: docker Time Zone 설정

---

client/src/App.tsx
client/src/components/sections/MainContent.tsx
client/src/store/useVisitStore.ts

-   close #323 
-   localStore에 visit-flag를 생성하여 첫방문 체크를 했습니다.
-   about페이지에서 메인페이지에 접근하기 위해서 아래로 내려가있던 스크롤이 메인페이지에서도 그대로 유지되어 메인페이지 접근 시 해당 스크롤 위치까지 내려가는 현상이 있어서 수정했습니다.
-   useVisitStore를 생성하여 hasVistied 상태를 저장하고 localStore에 flag를 생성하도록 구현했습니다.
```
import { create } from "zustand";
import { persist, createJSONStorage } from "zustand/middleware";
interface VisitState {
hasVisited: boolean;
setVisited: () => void;
}
export const useVisitStore = create<VisitState>()(
persist(
(set) => ({
hasVisited: false,
setVisited: () => set({ hasVisited: true }),
}),
{
name: "visit-flag",
storage: createJSONStorage(() => localStorage),
}
)
);
```
-  메인페이지 접근 시 스크롤을 최상단으로 올리기 위해 MainContent.tsx에 useEffect를 활용하여 스크롤을 올렸습니다.

✨ feat: 첫 방문 사용자 about페이지로 리다이렉트

---

server/src/main.ts

FE팀의 요청으로 `http://localhost:4173` 포트를 허용처리 하였습니다.

📦 chore: vite 개발용 포트 cors 허용

---

client/src/components/common/Card/PostCardSkeleton.tsx
client/src/components/sections/AnimatedPostGrid.tsx
client/src/components/sections/TrendingSection.tsx

```
<div className="flex flex-1 md:mt-4 md:p-6 bg-white rounded-2xl transition-all duration-300" style={sectionStyle}>
{isLoading || !posts.length ? <PostGridSkeleton count={4} /> : <AnimatedPostGrid posts={posts} />}
</div>
```
- 기존에 스켈레톤 UI가 나오도록 하는 조건이 isLoading이 true일때와 post.length가 없을때 나오로독 했습니다.
- 여기서 문제가 post가 없을때 0이 들어오게 되고 false로 잡히게 되어 계속 스켈레톤 UI만 나오도록 구현이 되어있었습니다.
```
<div className="flex flex-1 md:mt-4 md:p-6 bg-white rounded-2xl transition-all duration-300" style={sectionStyle}>
{isLoading ? <PostGridSkeleton count={4} /> : <AnimatedPostGrid posts={posts} />}
</div>
```
- 처럼 length에 대한 검사는 AnimatedPostGrid로 넘겨 에러문구가 나오도록 수정했습니다.
```
const PostGridSkeleton = ({ count = 8 }) => {
return (
<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6"> …
```

🐛 fix: 트랜딩 포스트가 없을 때 EmptyPost 컴포넌트가 나오지 않던 버그 수정 & 스켈레톤 UI가 나오지 않던 버그 수정

---

server/src/chat/chat.gateway.ts
server/src/chat/chat.type.ts
server/src/chat/scheduler/chat.scheduler.ts

-   close #377
```typescript
export type BroadcastPayload = {
messageId: string;
userId: string;
username: string;
message: string;
timestamp: Date;
};
```
채팅 메시지에 사용되는 `BroadcastPayload` 타입이 변경되었습니다.
추가된 행은 아래와 같습니다.
- `messageId`: 각 메시지마다 별도로 가지는 고유 ID. **채팅 전송 여부 확인에 사용 됨.**
- `userId`: 채팅을 보낸 사용자를 구분하기 위한 고유 ID. **자신의 채팅을 구분하기 위해 사용됨.**

✨ feat: 채팅 낙관적 업데이트를 지원하기 위한 채팅 페이로드 변경

---

server/src/migration/MigrateTagsToManyToMany1620000000000.ts

현재 저희 서버(TypeORM)레벨 에서 사용되는 Collation와, DB에 설정되어있는 기본 Collation이 다릅니다.
이에 따라 Migration이 실행되며 생성된 `tag` 테이블과, 기존에 존재하던 `tag_map` 테이블의 비교 연산이 수행되지 못해 Migration이 제대로 실행되지 못하였고, 이를 임의로 재실행 하자 쿼리가 끝까지 실행되지 못한채로 완료 로그가 출력되는 현상을 확인했습니다.
- TypeORM `synchronize` 에 의해 생성된 테이블의 Collation (`utf8mb4_0900_ai_ci`)
- RDBMS 기본 설정 값 Collation (`utf8mb4_unicode_ci`)
이에 따라 Migration시 생성되는 테이블들의 Collation을 별도로 기존 값인 `utf8mb4_0900_ai_ci` 맞추도록 별도로 명시해주는 구문을 추가하였습니다.
> [!TIP]
_테스트 환경에서는 왜 됐었음?_
확인 결과 제가 사용하는 로컬 DB는 기본값이 TypeORM의 기본값과 일치하였고, 이에 따라 로컬 테스트시에는 아무런 문제가 발생하지 않은 것으로 보입니다.

🐛 fix: Collation이 다르게 적용되던 부분 수정

---

server/src/common/email/email.service.ts

🐛 fix: 메일 내 회원 가입완료 링크 수정

---

server/src/user/api-docs/oAuth.api-docs.ts
server/src/user/constant/oauth.constant.ts
server/src/user/controller/oauth.controller.ts
server/src/user/dto/request/oauth-type.dto.ts
server/src/user/module/user.module.ts
server/src/user/provider/github.provider.ts
server/src/user/provider/google.provider.ts
server/src/user/provider/oauth-provider.interface.ts
server/src/user/service/oauth.service.ts

- #333 
각 프로바이더별로 OAuth flow에서 사용되는 데이터들과 반환받는 프로필 데이터가 다름에 따라, 사전에 타입(`OAuthTokenResponse`, `ProviderData`, `UserInfo`)을 지정해두고 해당 타입을 반환하는 형태로 코드를 변경하였습니다.
기존에 설계된 OAuthService의 플로우 스펙을 만족하는 `GithubOAuthProvider`를 작성하였습니다.
기존 Google OAuth와 대부분이 동일합니다. (주고받는 데이터, 데이터 빌딩 과정 등은 다릅니다.)
> **로그인 처리, Migraiton 작성은 다음 PR에서 일괄 처리하겠습니다 :)**

✨ feat: Github OAuth 회원가입 API 구현

---

.github/workflows/deploy_feed-crawler.yml
.github/workflows/deploy_server.yml

-   close #328
-   운영 인스턴스의 Docker Builder Cache가 인스턴스 용량만큼 차버려서 더 이상 빌드가 안 되는 문제가 있었다.
- 빌드가 되지 않아 코드 병합이 안 되는 문제가 있어 이 문제를 해결하고자 빌드 캐시를 지우도록 바꿨다.
-   도커 CI/CD로 도커 컴포즈 실행 후 빌더 지우도록 CI/CD 구현

📦 chore: docker builder 운영 환경 용량 부족 문제 해결

---

docker-compose/docker-compose.prod.infra.yml
docker-compose/prometheus.yml
server/package-lock.json
server/package.json
server/src/app.module.ts
server/src/chat/chat.gateway.ts
server/src/common/logger/logger.interceptor.ts
server/src/common/metrics/metrics.interceptor.ts
server/src/common/metrics/metrics.module.ts

-   close #390
- 프로메테우스는 메트릭을 수집하는 애플리케이션이다.
- 서버에 단순히 프로메테우스를 설치만한다 해서 메트릭을 수집할 수 없다.
- 밑에서 나오는 Node_Exporter나 애플리케이션단에서 메트릭을 추출해서 프로메테우스에서 저장하는 방식이다. 하나의 메트릭 데이터베이스라 생각하면 된다. 그렇기에 데이터는 외부에서 측정해야 한다.
- 프로메테우스를 공부하기 전에는 프로메테우스 자체가 데이터 수집 툴인줄 알았는데 아니었다.
-   프로메테우스를 사용하여 메트릭을 수집하는 방식을 학습하는 도중 Node_Exporter라는 것이 무엇인지 궁금했다.
- Node_Exporter는 애플리케이션단에서 얻기에는 적합하지 않은 시스템 하드웨어 메트릭(CPU, 메모리, 디스크) 정보를 수집하는 용도이다.
- 작업에서는 Node_Exporter를 통해 시스템 하드웨어 메트릭과 NestJS에서는 @willsoto/nestjs-prometheus 라이브러리를 사용하여 애플리케이션 메트릭을 수집하도록 했다.
- 위에서 메트릭 데이터베이스인 프로메테우스에 저장된 메트릭을 보기 좋게 시각화 하는 툴이다.
개인적으로 필요하다고 생각되는 것들을 애플리케이션 층에서 메트릭을 수집하도록 했다.
1. API마다 요청 전체 횟수
2. API마다 요청 실패 횟수 (응답 코드 500 이상)
3. API마다 요청 성공 횟수
4. 채팅 전체 개수
5. 현재 채팅 접속 인원 수
6. API마다 요청 성공 응답 시간
-   docker compose 프로메테우스, 그라파나, Node_Exporter 추가
- 프로메테우스 설정 …

✨ feat: 프로메테우스 + 그라파나 모니터링 시스템 구축

---

feed-crawler/package-lock.json
feed-crawler/package.json
feed-crawler/src/claude.service.ts
feed-crawler/src/common/logger.ts

- close #408
로그 수집이 중요한 Feed Crawler의 특성을 고려하여 Server와 동일하게 `winston-daily-rotate-file`를 적용하여 일별로 로그파일을 관리 하도록 했습니다.
불필요한 try - catch 구문을 제거 하였습니다.

♻️ refactor: feed crawler 로그 수집 개선

---

server/src/user/module/user.module.ts
server/src/user/scheduler/user.scheduler.ts

-  #396 
`resetExpiredStreaks` 메서드는 매 시 자정에 `lastActivate` 컬럼을 기반으로 streak을 유지할지, 0으로 초기화 할지 결정합니다. 스케줄러의 로직 흐름은 아래와 같습니다.
> 1. `currentStreak`이 0이 아니고, `lastActivate`가 0이 아닌 모든 사용자를 조회.
> 2. `lastActivate`가 어제보다 이전인 사용자들을 필터링.
> 3. 해당 사용자들의 streak 수치를 0으로 초기화.

✨ feat: 사용자 활동정보 업데이트 스케줄러 작성

---

server/src/comment/api-docs/getComment.api-docs.ts
server/src/comment/controller/comment.controller.ts
server/src/comment/dto/request/get-comment.dto.ts
server/src/comment/repository/comment.repository.ts
server/src/comment/service/comment.service.ts
server/test/comment/dto/comment-get.dto.spec.ts
server/test/comment/e2e/get.e2e-spec.ts
server/test/like/e2e/likeCreate.e2e-spec.ts

-   close #379
-   feed detail API에 댓글 정보를 제공할지, comment 조회 API를 만들지 고민을 헀다.
- 댓글 도메인을 만들어뒀기에 RestAPI 원칙에 따라 댓글을 조회할 수 있도록 하는 것이 맞다고 생각했다.
-   comment 조회 API 구현
- comment 조회 테스트 구현

✨ feat: 댓글 조회 API 구현

---

.github/workflows/deploy_infra.yml

-   close #328
-   기존에는 APP(NestJS)와 Feed Crawler, FE 코드가 변경되었을 경우 CI/CD가 적용되도록 하였지만, 운영 환경에서의 docker-compose.prod.infra.yml의 인프라가 추가되었을 경우 CI/CD가 안 돼서 수동으로 인프라들을 위한 도커 실행을 진행했어야 했다.
- 이 방식에 번거로움을 느껴서 조금 더 간편하게 수행하고자 Github CI/CD를 구현했다.
-  Dockerfile을 통한 빌드를 하는 경우는 이미 APP 배포와 Feed Crawler 배포에서 수행하기 때문에 --build 옵션을 제거했다.
-   docker-compose 운영 환경 인프라 자동 배포 기능 추가

📦 chore: docker-compose production 환경 인프라 추가시 자동 배포 구현

---

client/src/components/auth/AuthSocialLoginButtons.tsx
client/src/constants/endpoints.ts
client/src/pages/OAuthSuccessPage.tsx
client/src/routes/index.tsx
server/src/user/module/user.module.ts

- close #407 
- OAuth 로그인 URL이 하드코딩되어 있어 환경에 따른 관리가 어려움
- endpoints.ts에 통합하여 일관된 API 엔드포인트 관리 필요
- `endpoints.ts`에 `OAUTH` 객체 추가하여 OAuth 관련 엔드포인트 상수화
- `AuthSocialLoginButtons.tsx`에서 하드코딩된 `https://denamu.site/api/oauth` URL을 `BASE_URL + OAUTH.LOGIN` 형태로 변경
- 환경에 따른 동적 URL 처리가 가능하도록 개선

✨ feat: OAuth 로그인 API 연동 및 백엔드 보완
